## 3.1 ソート：問題にチャレンジする前に
- 計算量と安定性
- データの列を保持する1つの配列以外にメモリが必要にならないか
- 入力データの特徴が計算量に影響しないか

## 3.2 挿入ソート

In [45]:
import pandas as pd
import numpy as np
import random

In [46]:
rand_list = np.random.choice(np.arange(100), 100, replace=False)

In [47]:
rand_list

array([98, 32, 35,  8, 75, 56, 16,  4, 23, 69, 38, 45, 97, 58, 30, 84, 83,
       39, 88, 41, 37, 46, 62, 40, 53, 26, 63, 13,  5, 55, 42, 61, 90, 54,
       36, 47, 52, 70, 24, 15, 50,  3,  9, 18, 86, 79, 99,  1, 80, 77, 22,
       28, 91, 81, 34, 51, 19, 74, 57,  2, 12, 82, 64, 10, 67, 17, 66, 31,
       96, 94, 33, 68, 20, 11, 65, 43, 25, 14,  0, 27, 87, 85,  7, 76, 60,
       93, 72, 95, 49, 29, 21, 71, 89,  6, 92, 59, 73, 78, 44, 48])

In [41]:
N = 10
for i in range(N -1):
    vec = rand_list[i]
    j = i - 1
    while j >= 0 and rand_list[j] > vec:
        rand_list[j+1] = rand_list[j]
        j -= 1
    rand_list[j+1] = vec

In [42]:
rand_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 85])

In [49]:
def insertion_sort(num_array):
    len_array = len(num_array)
    for i in range(len_array):
        value = num_array[i]
        j = i - 1
        while j >= 0 and num_array[j] > value:
            num_array[j+1] = num_array[j]
            j -= 1
        num_array[j+1] = value
    return num_array

In [50]:
insertion_sort(rand_list)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [61]:
rand_list = np.random.randint(0, 100, 100)

In [63]:
insertion_sort(rand_list)

array([ 0,  1,  1,  2,  2,  2,  3,  4,  4,  5,  6,  9,  9, 10, 10, 11, 13,
       14, 15, 15, 16, 18, 18, 19, 19, 20, 21, 22, 24, 24, 24, 24, 27, 27,
       28, 29, 29, 34, 34, 35, 35, 36, 37, 38, 38, 39, 41, 41, 41, 42, 46,
       46, 46, 48, 49, 50, 51, 52, 52, 53, 54, 54, 54, 57, 58, 58, 61, 62,
       62, 64, 65, 67, 70, 70, 70, 72, 73, 75, 75, 76, 76, 77, 77, 79, 79,
       80, 83, 84, 84, 87, 87, 88, 88, 90, 91, 93, 94, 95, 97, 97])

In [ ]:
np